#!/bin/bash 
# Based on script found in the Gentoo wiki
# Example usage: ./backlight down 50

Val=$2 

read -r MaxVal < "/sys/class/backlight/intel_backlight/max_brightness"
read -r CurrVal < "/sys/class/backlight/intel_backlight/brightness"

if [[ "$1" = "up" ]]; then
   NewVal=$(($CurrVal + $Val)); 
elif [[ "$1" = "down" ]]; then
   NewVal=$(($CurrVal - $Val)); 
fi
echo $Val 

# Set it to the threshold of the max value. 
ThresholdVal=$(($NewVal<$MaxVal?$NewVal:$MaxVal)) 
echo $ThresholdVal 

echo -n $ThresholdVal > /sys/class/backlight/intel_backlight/brightness 

logger "[ACPI] brightnessup |$CurrVal| |$NewVal| |$ThresholdVal|"
