#!/usr/bin/env bash
# Just for persistent game saving in "Cataclysm: Dark Days Ahead"
# mjturt

function save() {
   cp -r ~/.cataclysm-dda/save ~/.cataclysm-dda/customsaves/save-"$(date +%d%m%y-%H%M%S)"
}

function tester() {
   while kill -0 $PID1 > /dev/null 2>&1; do
      sleep 1
   done
   kill $PID2 
}

function play() {
   cataclysm-tiles &
   PID1=$!
   #(while kill -0 $PID1 > /dev/null 2>&1; do
   (while true; do
      sleep 300
      save
   done) &
   PID2=$!
   tester
}


if [ "$#" -ne 1 ]; then
   play
   printf "Rsync save to cloud? (y/n) "
   read -r cloud
   if [[ $cloud = "y" ]]; then
      rsync --recursive --delete ~/.cataclysm-dda/save ~/cloud/cdda
   fi
else
   case "$1" in
      -s|--save)
         save
         exit 0 ;;
      *)
         exit 1 ;;
   esac
fi
