#!/bin/bash

echo -ne "\e[?25l" # hide cursor

fbvis /home/mjt/cloud/images/wallpapers/fb/pixel.png << EOF
q
EOF

shift
export FBTERM_BACKGROUND_IMAGE=1
exec fbterm --font-names="ShureTechMono NF" --font-size=13  "$@"
