#!/bin/sh
# Lock script

xidlehook \
   --time 5 \
   --timer 'xrandr --output "$(xrandr | grep -e primary -e connected | grep -v disconnected | cut -d " " -f 1)" --brightness 1; /home/mjt/bin/lock' \
   --notify 10 \
   --notifier  'xrandr --output "$(xrandr | grep -e primary -e connected | grep -v disconnected | cut -d " " -f 1)" --brightness .1' \
   --canceller 'xrandr --output "$(xrandr | grep -e primary -e connected | grep -v disconnected | cut -d " " -f 1)" --brightness 1' \
   --not-when-fullscreen 
