#!/usr/bin/env bash
# Torrent magnet link -> .torrent file based on Arch wiki example
# usage: ./magnet "magnet_link" --here (optional)

case "$2" in
   --here)
      ;;
   *)
      watch=/home/mjt/cloud/watch-torrent
      cd $watch
      ;;
esac
[[ "$1" =~ xt=urn:btih:([^&/]+) ]] || exit;
echo "d10:magnet-uri${#1}:${1}e" > "meta-${BASH_REMATCH[1]}.torrent"
