#!/bin/sh
# mjturt
if [[ -d /mnt/storage/music/youtube ]]; then
   cd /mnt/storage/music/youtube || exit
   youtube-dl --metadata-from-title "%(artist)s - %(title)s" --extract-audio --audio-format mp3 --add-metadata "$1" 
fi
