#!/usr/bin/env bash

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

if [ "$(hostname)" = "yoga" ]; then
    polybar dwmyoga &
    polybar dwmhdmi &
elif [ "$(hostname)" = "r5" ]; then
    polybar dwm &
elif [ "$(hostname)" = "tp" ]; then
    polybar dwmtp &
fi
