#!/bin/sh
# Syntax highlighting with highlight
# Usage with less:
# export LESSOPEN="|~/sh/syntax-highlighting %s"
case "$1" in
   *.awk|*.groff|*.java|*.js|*.m4|*.php|*.pl|*.pm|*.pod|*.sh|\
   *.ad[asb]|*.asm|*.inc|*.[ch]|*.[ch]pp|*.[ch]xx|*.cc|*.hh|\
   *.lsp|*.l|*.pas|*.p|*.xml|*.xps|*.xsl|*.axp|*.ppd|*.pov|\
   *.diff|*.patch|*.py|*.rb|*.sql|*.ebuild|*.eclass)
      highlight -O truecolor --style base16/gruvbox-hard --force "$1"
   ;;
   .bashrc|.bash_aliases|.bash_environment|.zshrc|*.zsh|PKGBUILD)
      highlight -O truecolor --style base16/gruvbox-dark-hard --force -S sh "$1"
   ;;
   .vimrc)
      highlight -O truecolor --style base16/gruvbox-dark-hard --force -S vimscript "$1"
   ;;
   *)
      head -1 "$1" | grep -e "#\!/usr/bin/env bash" -e "#\!/bin/sh" -e "#\!/bin/bash" > /dev/null
      if [ "$?" -eq "0" ]; then
         highlight -O truecolor --style base16/gruvbox-dark-hard --force -S sh "$1"
      else
         highlight -O xterm256 --style base16/gruvbox-dark-hard --force "$1"
      fi
esac
exit 0
