# ~/.zshrc (Thinkpad)
# -------------------
# mjturt
# In this file only host-specific configurations

HISTFILE=~/.zsh/history
HISTSIZE=1000
SAVEHIST=1000

export ZSH=/home/mjt/.oh-my-zsh
export EDITOR="vim"

zstyle ':completion:*' rehash true

ZSH_THEME="powerlevel9k/powerlevel9k"
CASE_SENSITIVE="true"
plugins=(git)

source $ZSH/oh-my-zsh.sh
source /etc/profile.d/vte.sh

POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\ue0cc'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\ue0c7'

POWERLEVEL9K_CONTEXT_TEMPLATE="%n@%m"

POWERLEVEL9K_TIME_FOREGROUND='black'
POWERLEVEL9K_TIME_BACKGROUND='028'
POWERLEVEL9K_OS_ICON_FOREGROUND='black'
POWERLEVEL9K_OS_ICON_BACKGROUND='094'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='026'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='black'
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='026'
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='black'
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND='red'
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND='226'
POWERLEVEL9K_STATUS_OK_BACKGROUND='026'
POWERLEVEL9K_STATUS_OK_FOREGROUND='046'
#POWERLEVEL9K_STATUS_ERROR_BACKGROUND='026'
#POWERLEVEL9K_STATUS_ERROR_FOREGROUND='black'
POWERLEVEL9K_DISK_USAGE_NORMAL_BACKGROUND='028'
POWERLEVEL9K_DISK_USAGE_NORMAL_FOREGROUND='black'
POWERLEVEL9K_BATTERY_LOW_BACKGROUND='red'
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='yellow'
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND='green'
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND='yellow'
POWERLEVEL9K_BATTERY_LOW_FOREGROUND='black'
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND='black'
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND='black'
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND='black'
POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="green"
POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="black"
POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="white"
POWERLEVEL9K_LOAD_WARNING_BACKGROUND="black"
POWERLEVEL9K_LOAD_WARNING_FOREGROUND="white"
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="black"
POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="white"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time context dir vcs newline os_icon root_indicator)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(dir_writable status disk_usage)

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.oh-my-zsh/plugins/calc/calc.plugin.zsh

bindkey "$terminfo[kcuu1]" up-history
bindkey "$terminfo[kcud1]" down-history

alias upgrade="sudo pacman -Syu"

# Sourcing the rest of files

source $HOME/.zsh/evars.zsh
source $HOME/.zsh/functions.zsh
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/private.zsh
source $HOME/.zsh/keybindings.zsh
