#! /usr/bin/env bash
#┃ ~/.config/bspwm/bspwmrc
#┣━━━━━━━━━━━━━━━━━━━━━━━━
#┃ mjturt

### Start sxhkd
sxhkd &

### Host specific configurations
if [[ "$(hostname)" = "r5" ]]; then
   bspc monitor DVI-I-2 -d 1 2 3 4 5 6 7 8
   #bspc monitor DVI-I-1 -d 6 7 8 9 0
   bspc config focus_follows_pointer true
elif [[ "$(hostname)" = "tp" ]]; then
   bspc monitor eDP-1 -d 1 2 3 4 5 6
   bspc monitor DP-2 -d 7 8 9
   bspc config focus_follows_pointer false
fi

### Basic settings
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config pointer_follows_monitor true

bspc config normal_border_color "#222222" 
bspc config active_border_color "#222222" 
bspc config focused_border_color "#87875f" 
bspc config presel_feedback_color "#87875f"

### Rules
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Rambox desktop='^2'
bspc rule -a Steam desktop='^7'
bspc rule -a Nitrogen state=floating
bspc rule -a ColorGrab state=floating
bspc rule -a Colorgrab state=floating
bspc rule -a Yad state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pinentry-gtk-2 state=floating
bspc rule -a MainApp state=floating
bspc rule -a JetBrains Privacy Policy state=floating
bspc rule -a propertymanager.MainApp state=floating


### Start polybar with starting script
poly bspwm
