#! /bin/sh
#┃ ~/.config/bspwm/bspwmrc
#┣━━━━━━━━━━━━━━━━━━━━━━━━
#┃ mjturt

### Start sxhkd
sxhkd &

### Host specific configurations
source ~/.config/bspwm/bspwmrc.host

### Basic settings
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config pointer_follows_monitor true

bspc config normal_border_color "#222222" 
bspc config active_border_color "#222222" 
bspc config focused_border_color "#87875f" 
bspc config presel_feedback_color "#87875f"

### Rules
bspc rule -a Gimp desktop='^4' state=floating follow=on
#bspc rule -a Rambox desktop='^6'
bspc rule -a Steam desktop='^7'
bspc rule -a Nitrogen state=floating
bspc rule -a ColorGrab state=floating
bspc rule -a Colorgrab state=floating
bspc rule -a Yad state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pinentry-gtk-2 state=floating

### Start polybar with starting script
poly bspwm
