#! /bin/sh
#┃ ~/.config/bspwm/bspwmrc
#┣━━━━━━━━━━━━━━━━━━━━━━━━
#┃ mjturt

sxhkd &

source ~/.config/bspwm/bspwmrc.host

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^3'
bspc rule -a Rambox desktop='^2'
bspc rule -a Steam desktop='^7'
bspc rule -a Nitrogen state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true

poly bspwm

bspc config top_padding 20
